#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config top_padding		18

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer	true
bspc config focused_border_color    "#a6a28c"
bspc config active_border_color     "#7d7a68"
bspc config normal_border_color     "#6e6b5e"

#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d $(echo '\uf109') $(echo '\uf121') $(echo '\uf120') $(echo '\uf07c') $(echo '\uf0ac') $(echo '\uf0c3') $(echo '\uf141') $(echo '\uf001')
bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a gimp floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a thunderbird desktop=^9
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a vlc floating=on

feh --bg-scale Pictures/bond.png --force-aliasing
compton -b
xsetroot -cursor_name left_ptr

unclutter &
caffeine &
panel &
conky &
xflux -l 46.5 -g 6.6
#thunderbird &
#source ~/.config/bar/barrc | lemonbar -f "-misc-fontawesome-medium-r-normal--0-0-0-0-p-0-iso10646-1" -p -B "#DD2C3B4E" &
#source ~/.config/bar/barrc | lemonbar -p &
